# fly.toml app configuration file generated for yerba-dev on 2023-06-19T23:37:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yerba-dev"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "15s"


[build]
dockerfile = "server/docker/Dockerfile"

[env]
DB_ADDR = "file:/data/sqlite2.db"
SPACES_DIR = "/data/2/spaces"
LOG_LEVEL = "info"
NODE_ENV = "production"
PORT = "8080"
VITE_SERVER_BASE = "yerba-dev.fly.dev"

[mounts]
source = "yerbadev"
destination = "/data"

[processes]
server = "server"
python = "python server.py"

# [[services]]
# http_checks = []
# internal_port = 8080
# protocol = "tcp"
# script_checks = []

[http_service]
processes = ["server"]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[services]]
processes = ["python"]
internal_port = 5001
[services.concurrency]
type = "requests"
hard_limit = 25
soft_limit = 20
min_machines_running = 1


[experimental]
auto_rollback = true
entrypoint = ["entrypoint.sh"]
