# fly.toml app configuration file generated for yerba-dev on 2023-06-19T23:37:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yerba-dev"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "15s"

[experimental]
auto_rollback = true

[build]
dockerfile = "server/docker/Dockerfile"

[env]
DB_ADDR = "/data/1/db/sqlite.db"
LOG_LEVEL = "info"
NODE_ENV = "production"
PORT = "8080"
SPACES_DIR = "/data/1/spaces"

[mounts]
source = "yerba-server"
destination = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "requests"
hard_limit = 250
soft_limit = 200

[[services]]
protocol = "tcp"
internal_port = 8080
auto_stop_machines = true
auto_start_machines = true

[[services.ports]]
port = 443

[[services.ports]]
port = 8080
