[package]
name = "server"
version = "0.0.1"
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
rspc = { workspace = true, features = [
    "uuid",
    "chrono",
    "tracing",
    "alpha",
    "unstable",
    "anyhow",
    "axum",
] }
custom-prisma = { path = "../crates/prisma" }
anyhow = { version = "1.0", features = ["backtrace"] }
httpz = { workspace = true, features = ["axum"] }

reqwest = { version = "0.11.18", features = ["json"] }
axum = { version = "0.6.18", features = ["multipart"] }
tokio = { workspace = true, features = [
    "sync",
    "rt-multi-thread",
    "io-util",
    "macros",
    "time",
    "fs",
    "rt",
    "signal",
] }
ctrlc = "3.3.1"
http = "0.2.9"
tower-http = { version = "0.4.0", features = ["fs", "cors"] }
mime_guess = "2.0.4"
prisma-client-rust = { workspace = true, features = ["rspc"] }
specta = { workspace = true }
base64 = "0.21.2"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.25", features = ["serde"] }
serde_json = "1.0"
futures = "0.3"
rmp = "^0.8.11"
rmp-serde = "^1.1.1"
blake3 = "1.3.3"
hostname = "0.3.1"
uuid = { version = "1.3.3", features = ["v4", "serde"] }
sysinfo = "0.28.4"
thiserror = "1.0.40"
include_dir = { version = "0.7.3", features = ["glob"] }
async-trait = "^0.1.68"
image = "0.24.6"
webp = "0.2.2"
tracing = { git = "https://github.com/tokio-rs/tracing", rev = "29146260fb4615d271d2e899ad95a753bb42915e" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing", rev = "29146260fb4615d271d2e899ad95a753bb42915e", features = [
    "env-filter",
] }
async-stream = "0.3.5"
once_cell = "1.17.2"
ctor = "0.1.26"
globset = { version = "^0.4.10", features = ["serde1"] }
itertools = "^0.10.5"
enumflags2 = "0.7.7"
uhlc = "0.5.2"
http-range = "0.1.5"
mini-moka = "0.10.0"
serde_with = "2.3.3"
dashmap = { version = "5.4.0", features = ["serde"] }
notify = { version = "5.2.0", default-features = false, features = [
    "macos_fsevent",
], optional = true }
static_assertions = "1.1.0"
serde-hashkey = "0.4.5"
normpath = { version = "1.1.1", features = ["localization"] }
tracing-appender = { git = "https://github.com/tokio-rs/tracing", rev = "29146260fb4615d271d2e899ad95a753bb42915e" } # Unreleased changes for log deletion
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
jsonwebtoken = "8.3.0"
